#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>


/* Section generated by pkgbuild, do not edit */
/* .Call calls */
extern SEXP parse_from_str_(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"parse_from_str_", (DL_FUNC) &parse_from_str_, 1},
    {NULL, NULL, 0}
};
/* End section generated by pkgbuild */

void R_init_rtoml(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
