#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>


/* Section generated by pkgbuild, do not edit */
/* .Call calls */
extern SEXP read_toml_(SEXP);
extern SEXP parse_toml_(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"parse_toml_", (DL_FUNC) &parse_toml_, 1},
    {"read_toml_",  (DL_FUNC) &read_toml_,  1},
    {NULL, NULL, 0}
};
/* End section generated by pkgbuild */

void R_init_rtoml(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
